### ISSUE TITLE
Subgrid not displayed correctly

### ISSUE THREAD

**Issue by pab74** [MaTeMaTuK/pcf-universal-gantt-chart#1]
Hello, first of all nice work, well done and thanks for sharing. I noticed that the gantt is not displayed correctly in a subgrid, even if i set 20 rows in the subgrid formatting options. I attach a video. 
Paolo
https://www.loom.com/share/60809dc8390d4fe696acfa2b150bcf1c

**Comment by MaTeMaTuK** [comment]
Hi @pab74,
Is it with wave 2 2020 or not ?

**Comment by pab74** [comment]
Hi,
this is Wave 2 2020 release enabled
[image: image.png]

Il giorno lun 7 set 2020 alle ore 19:38 MaTeMaTuK <notifications@github.com>
ha scritto:

**Comment by MaTeMaTuK** [comment]
Hi @pab74,
I have added subgrid mode and now you might test it.
![image](https://user-images.githubusercontent.com/26743903/93709554-cb488a00-fb47-11ea-9826-06c36d4b2aec.png)
![image](https://user-images.githubusercontent.com/26743903/93709579-ef0bd000-fb47-11ea-8633-54dd70a293c3.png)

**Comment by pab74** [comment]
Cool!!! great job. it seems ok now. thanks a lot
