### ISSUE TITLE
Use with "Date Only" Columns instead of "Date and Time"

### ISSUE THREAD

**Issue by Daniel-12tg** [MaTeMaTuK/pcf-universal-gantt-chart#11]
Great control, thanks! I was wondering is there a way to adapt it to make use of "Date Only" columns? I tried to find a way to use Calculated Fields to create a "Date and Time" column from my "Date Only" column but was not successful. Thanks,
Daniel

**Comment by MaTeMaTuK** [comment]
Hi @Daniel-12tg,
You could edit ControlManifest.Input.xml and build control with data only flelds if you have basic programming level. 
Also you may use sync workflow for DateTime column coping as workaround.

P.S. Perhaps you are trying to use Microsoft Dynamics 365 Project Operations with my chart. Unfortunately this component aren't adapted with Project Operations fully and that module is very complicated for out of box customization.

**Comment by Daniel-12tg** [comment]
Hi @MaTeMaTuK, thanks for your quick response. I'll try editing the xml file you indicated.

FYI I am using Microsoft PowerApps, Model-Driven app.
