### ISSUE TITLE
solution.zip is missing

### ISSUE THREAD

**Issue by mJeromeDiaz** [MaTeMaTuK/pcf-universal-gantt-chart#12]
Hi, thanks for your works.
I cannot use your work because the solution.zip file is missing.
Where is it ?

**Comment by MaTeMaTuK** [comment]
Hi @mJeromeDiaz ,
Could you please check release assets 
https://github.com/MaTeMaTuK/pcf-universal-gantt-chart/releases/tag/v1.3
