### ISSUE TITLE
How to localize month names?

### ISSUE THREAD

**Issue by radeknovak** [MaTeMaTuK/pcf-universal-gantt-chart#14]
Hi @MaTeMaTuK,

I really like your PCF component.
I have only one question.
How can I localize month names in this component?
I was successfully localized labels like Start, End, Half day, etc. using  RESX, but I didn't find any place for month names localization.

Thank you for your hard work and I appreciate your help.

Radu.
![chrome_2021-06-10_14-51-16](https://user-images.githubusercontent.com/6222770/121528226-90e78b80-c9fb-11eb-988b-1d3eae39e9da.png)

**Comment by MaTeMaTuK** [comment]
Hi @radeknovak,
I use Intl.DateTimeFormat for localisation there.
I will take a look how We can setup this value.

**Comment by TheDarktor** [comment]
I really like your pcf too, but i can't change the month names too. I appreciate your help too.

**Comment by MaTeMaTuK** [comment]
Thanks guys for feedback.
Okay I have found the approach for months localisation via native tools.
![image](https://user-images.githubusercontent.com/26743903/121731740-020d6880-cafa-11eb-8980-b78f3ef58d5d.png)
See follow

**Comment by MaTeMaTuK** [comment]
File **index.ts**
Add new method 
```
  private async getLocalCode(context: ComponentFramework.Context<IInputs>) {
    try {
      const languages = await context.webAPI.retrieveMultipleRecords(
        "languagelocale",
        `?$select=code&$filter=localeid eq ${context.userSettings.languageId}`
      );
      if (languages.entities.length > 0) {
        const code = languages.entities[0].code;
        return code;
      }
    } catch (e) {
      context.navigation.openErrorDialog(e);
    }

    return "en"; // English
  }
```
Call this method in updateViewAsync
`const locale = await this.getLocalCode(context);`
Set _locale_ value in to 
```
const gantt = React.createElement(UniversalGantt, {
        context,
        tasks,
        locale,
        ganttHeight,
        recordDisplayName,
        startDisplayName,
        endDisplayName,
        progressDisplayName,
        startFieldName: startField.name,
        endFieldName: endField.name,
        progressFieldName: progressFieldName,
        listCellWidth: listCellWidth,
        timeStep: context.parameters.timeStep.raw,
        rowHeight: rowHeight,
        headerHeight: headerHeight,
        isProgressing: !!progressField,
        viewMode: this._viewMode,
        includeTime: includeTime,
        crmUserTimeOffset: this._crmUserTimeOffset,
        fontSize,
        columnWidthQuarter,
        columnWidthHalf,
        columnWidthDay,
        columnWidthWeek,
        columnWidthMonth,
        onViewChange: this.handleViewModeChange,
      });

```
File universal-gantt.tsx
Add argumnet in UniversalGanttProps
`locale: string;`

Done!

**Comment by MaTeMaTuK** [comment]
I will add this solution in next release. 
P.S. Could you please share your resx file with localisation?

**Comment by radeknovak** [comment]
@MaTeMaTuK 
Thank you for your quick response and help.
There is the RESX source for Czech translation.
[UniversalGanttChartComponent.1029.zip](https://github.com/MaTeMaTuK/pcf-universal-gantt-chart/files/6646154/UniversalGanttChartComponent.1029.zip)

**Comment by TheDarktor** [comment]
Thank you for the suport. I really like your work!
There is the RESX source for Brazilian Portuguese translation.
[UniversalGanttChartComponent.1046.zip](https://github.com/MaTeMaTuK/pcf-universal-gantt-chart/files/6648309/UniversalGanttChartComponent.1046.zip)

**Comment by MaTeMaTuK** [comment]
@TheDarktor,
Thanks! I will add your translation also.

**Comment by MaTeMaTuK** [comment]
Fix has been added in new version. Please check
![image](https://user-images.githubusercontent.com/26743903/130397798-7be900aa-bca5-4798-b7cc-7f2080728ea2.png)
