### ISSUE TITLE
Custom Fetch for Subgrid

### ISSUE THREAD

**Issue by radeknovak** [MaTeMaTuK/pcf-universal-gantt-chart#15]
Hi @MaTeMaTuK 
We are solving following case now:
We dynamically change Fetch for subgrid data using custom filtering. 
```
var gridContext = formContext.getControl("GanttProjSubgrid");
gridContext.setFilterXml(fetchXML);
gridContext.refresh();
```
In this situation component doesn't render Gantt.
Is there a way to use custom Fetch for Subgrid Gantt?

**Comment by MaTeMaTuK** [comment]
setFilterXml is unsupported feature.
However you may try use another option. PCF control allows filtering. 
https://docs.microsoft.com/en-us/powerapps/developer/component-framework/reference/filtering
https://www.inogic.com/blog/2020/09/how-to-set-filters-in-pcf-dataset-control-using-setfilter-method/
