### ISSUE TITLE
Translation to Spanish

### ISSUE THREAD

**Issue by fgiammaria** [MaTeMaTuK/pcf-universal-gantt-chart#16]
Could you add the Spanish translation ???

The component is great!

Thanks in advance

Flavia

**Comment by MaTeMaTuK** [comment]
Hi Flavia,
Sure. I can include Spanish. However I need translations for following sentences.
_Are you sure?
day
Duration
day(s)
half of day
month
More Records
quarter of day
week_

**Comment by fgiammaria** [comment]
Thanks! You are crack!


Are you sure?    ¿Estás seguro?
day                        día
Duration              Duración
day(s)                   día(s)
half of day          medio día
month                  mes
More Records    Más Registros
quarter of day   cuarto de día
week                     semana

Thank you from Argentina 😉⚽



Flavia Giammaria
Solution Architect
Cel: +54 11 2521 0630
Skype: fgiammaria

[Linkedin]<https://www.linkedin.com/company/axxon-consulting>   [Facebook] <https://www.facebook.com/pages/Axxon-Consulting/196116037082801>    ***@***.***D77414.3A114FE0] <https://www.instagram.com/axxonconsulting/>
[Axxon]<https://axxonconsulting.com/>

**Comment by MaTeMaTuK** [comment]
You are welcome =) 
I will close this ticket after solution update.

**Comment by MaTeMaTuK** [comment]
Added. Please try new version
![image](https://user-images.githubusercontent.com/26743903/130397687-1bef97c5-0d76-4229-a341-3a75dcecbf17.png)
