### ISSUE TITLE
Control not showing up

### ISSUE THREAD

**Issue by VRADries** [MaTeMaTuK/pcf-universal-gantt-chart#17]
Hi, we are trying to add this control to our model driven app, but we can't get it to show.
It is set up as follows:
![image](https://user-images.githubusercontent.com/92166050/136571126-5805759b-6b50-485a-b791-ab30af18b73e.png)

But on the tasks page, nothing shows (while tasks have been created and show up on the grid view), we did notice some errors on the console though:
![image](https://user-images.githubusercontent.com/92166050/136571476-f3577db0-aa4e-4575-b8e8-e65d0f6addfd.png)

Did we miss a setup step?

**Comment by MaTeMaTuK** [comment]
Hi @VRADries,
Are title, end, start time exist in records?
Is it wave 2? 
Could you please share examples ?

**Comment by VRADries** [comment]
Hi @MaTeMaTuK ,
the tasks we are trying to show have the related field filled in, e.g.:
![image](https://user-images.githubusercontent.com/92166050/136756934-94b37e4f-f951-4c2a-911a-1a95637886e5.png)

Is just added a task on an Account, after it was added initially the Gantt shows correctly (due date was not filled in, so was set automatically to the start date):
![image](https://user-images.githubusercontent.com/92166050/136759616-144675bb-1d13-4d37-9ecf-5074b8b8ee85.png)
but when I refresh or change to table and back to Gantt, it disappears:
![image](https://user-images.githubusercontent.com/92166050/136759744-cba17629-38c7-4639-a425-9ce1568632c5.png)

The errors are the same for all cases (initially, on the account view with one task and after I added another task), so it seems the error is not related to missing info on the tasks themselves? 

I'm checking the version, but am assuming it's wave 2 indeed.

**Comment by MaTeMaTuK** [comment]
Hi @VRADries,
Sorry for late reply,
I see that you have an old version on screenshots.
Have you tried v1.4 ? I have tested v1.4 with wave 2

**Comment by MaTeMaTuK** [comment]
https://github.com/MaTeMaTuK/pcf-universal-gantt-chart/releases

**Comment by VRADries** [comment]
No problem @MaTeMaTuK ! :) 

We upgraded the environment and used the 1.4 but run into the same error.

**Comment by MaTeMaTuK** [comment]
Hi @VRADries,
Could you please test the 1.5 version.

**Comment by VRADries** [comment]
Hi @MaTeMaTuK , I tried the new version, but now I'm not able to link the fields (the option is greyed out):
![image](https://user-images.githubusercontent.com/92166050/138688044-c9d2cce3-c561-4cf4-8e9d-ac98ceed4d77.png)

When I use the first option and fill in a dummy value (to check if it would show), it does not get saved (got a general error one time, but can not replicate it).

**Comment by MaTeMaTuK** [comment]
I have checked that for view only. 
I will take a look on an entity control.

**Comment by VRADries** [comment]
When added as a custom control on a view:
![image](https://user-images.githubusercontent.com/92166050/138870929-4da9b5da-2f1d-4939-9e1a-342390174ee5.png)

I get the following error message when trying to display the control (one task was added but nothing showed):
![image](https://user-images.githubusercontent.com/92166050/138871125-3ca6a3cd-51d6-4e62-b95d-50bb60ca6622.png)

When I clicked on the URL to display the error:
![image](https://user-images.githubusercontent.com/92166050/138870569-48b4094c-6700-4700-8e25-251f06f4adb0.png)

So although it does not display, it seems to be a different error this time 😄

**Comment by MaTeMaTuK** [comment]
@VRADries :(
I will try find to way out.

**Comment by MaTeMaTuK** [comment]
Hi @VRADries,
Could you please try this ? 
[UniversalGanttChartSolution.zip](https://github.com/MaTeMaTuK/pcf-universal-gantt-chart/files/7499461/UniversalGanttChartSolution.zip)
?

**Comment by VRADries** [comment]
Alas, I get the same error 😞 
I used the same setup as in my previous message, I did not add any tasks, just trying to display the sample entries in the task list.

**Comment by VRADries** [comment]
@MaTeMaTuK 
Nevermind, I got it to work, first on opportunities and later tasks. Not sure what I did different but it shows up correctly.
We can now finally play around with the control haha, thanks a bunch! 😄
