### ISSUE TITLE
Enhancement: add the "Create new task" button on the bar

### ISSUE THREAD

**Issue by pab74** [MaTeMaTuK/pcf-universal-gantt-chart#2]
Hi,
It would be very useful, especcially for the subgrid, to have the possibility to create new tasks. The "+" button should open the quick create if available. Eventually also the selection of tasks would be useful and the corresponding "Delete" button on the bar.
thanks
Paolo

**Comment by MaTeMaTuK** [comment]
Hi @pab74 ,
I didn`t test it as subgrid and I recommend use Associated View on entity form.
![image](https://user-images.githubusercontent.com/26743903/92448170-e66adf80-f1c0-11ea-8eb0-eb88be171e96.png)

However, I will try to do special view for subgrid for this component. 
P.S. If you wanna delete record you should select a bar and press _Delete_ button

**Comment by pab74** [comment]
Hi,
thank you. However, the associated view on Activity doesn't allow to set
the completion percentage, because the activity entity has not such field.
Thanks anyway
BR
Paolo

Il giorno mar 8 set 2020 alle ore 10:01 MaTeMaTuK <notifications@github.com>
ha scritto:

**Comment by MaTeMaTuK** [comment]
Hi @pab74 ,
I hope, you don`t have any issues with ribbon and select functionality now.
I`m closing issue and I will rename v1.1-preview to v1.1.
Thanks
