### ISSUE TITLE
RTL support (Languages written from right to left)

### ISSUE THREAD

**Issue by alex188888** [MaTeMaTuK/pcf-universal-gantt-chart#3]
Hello,

Some short questions
1. We noticed that there is no support for RTL (the Gantt is displayed from end to beginning as well as the 'Progress Bar')
2. We could not figure out how we could translate some of the fields
3. Is there a way to hide the time from the view? Because we only deal with whole days

*RTL = Languages written from right to left (Hebrew, Arabic, etc.)

Thank you so much for this amazing thing

**Comment by MaTeMaTuK** [comment]
Hi @alex188888,
Thanks for your feedback.
1) Correct, It doesn't support RTL for now. Anyway, We may discuss  this feature
2) Chart takes field labels from crm. Other labels as "Weekly", "More Records" and others contain in localisation files. I can send a file with sentence and you may translate them
3) I may include this display time feature in the next release

**Comment by MaTeMaTuK** [comment]
RTL has been added. Please try a new version.
