### ISSUE TITLE
Cannot Change Row Height 

### ISSUE THREAD

**Issue by hmourad1** [MaTeMaTuK/pcf-universal-gantt-chart#4]
There should be an easy way to change the default row height

**Comment by MaTeMaTuK** [comment]
Hi,
Original [gantt ](https://github.com/MaTeMaTuK/gantt-task-react#StylingOption) supports this option.
I can add this option on this weekend.

**Comment by hmourad1** [comment]
Great! thank you for the support and amazing work on this.

**Comment by MaTeMaTuK** [comment]
Hi @hmourad1,
Could you please try a new version

**Comment by MaTeMaTuK** [comment]
@hmourad1 does it work well?

**Comment by MaTeMaTuK** [comment]
Case was resolved

**Comment by hmourad1** [comment]
> Hi @hmourad1,
> Could you please try a new version

Thank you so much, i will try and let you know

**Comment by hmourad1** [comment]
I finally had the chance to test out the changes. everything works well. Thank you very much.
