### ISSUE TITLE
Different colors ?

### ISSUE THREAD

**Issue by seb-imad** [MaTeMaTuK/pcf-universal-gantt-chart#5]
I am very interested in your gantt component.
Is it possible to have the background color associated to a field of the entity ?  Currently it seems that it is only a static value ?
Thank you.

**Comment by MaTeMaTuK** [comment]
Hi @seb-imad,
No. It`s not static value. Gantt chart retrieves entity color by default and creates palette colors via https://github.com/ant-design/ant-design-colors#readme by default
This picture shows task and activity records. 
![image](https://user-images.githubusercontent.com/26743903/92448170-e66adf80-f1c0-11ea-8eb0-eb88be171e96.png)
Other option is use progressColor, progressSelectedColor, backgroundColor, backgroundSelectedColor params.
However I didn't realise coloring by field value. I think about some text or option set field(or both of them) with basic color and use this basic color for palette.

**Comment by seb-imad** [comment]
Using an option set field of the entity is a good idea. With this method you can use the color of the option for the background.

In my use I have only one (custom) entity and I would like to have different colors according to a field "urgency" for instance (urgent --> red, normal --> green...). With an option field urgency it's fine.

**Comment by MaTeMaTuK** [comment]
Ok. I will add it in the next few weeks.

**Comment by MaTeMaTuK** [comment]
Hi,
Good news. It's almost done. But I'm still working on another feature for next release.
![image](https://user-images.githubusercontent.com/26743903/100981111-fd666700-354e-11eb-8dea-2e66cf7cd9cc.png)

**Comment by seb-imad** [comment]
Great !
I have a lot of other proposals if you need some challenge ;-).
Thank you.

**Comment by MaTeMaTuK** [comment]
Hi @seb-imad,
New version 1.3 is ready! Please test it

**Comment by seb-imad** [comment]
Thanks. I'm starting my tests and give you some news asap.

**Comment by seb-imad** [comment]
Everything seems good for me. Thanks for your help !
