### ISSUE TITLE
Vertical scroll

### ISSUE THREAD

**Issue by shreyb28** [MaTeMaTuK/pcf-universal-gantt-chart#7]
The gantt works well for a certain no of entries. After that due to the absence of a vertical scroll the chart is cut-off

**Comment by shreyb28** [comment]
![no scrollbar](https://user-images.githubusercontent.com/77260036/104682007-aac3c180-572e-11eb-9ad4-be47c0cb4968.png)

**Comment by shreyb28** [comment]
the horizontal scrollbar doesn't show either but work with the arrow keys.

**Comment by MaTeMaTuK** [comment]
Hi @shreyb28,
Could you share your gantt setup?

**Comment by shreyb28** [comment]
![image](https://user-images.githubusercontent.com/77260036/104861667-c8319f00-596b-11eb-834a-392ec555832b.png)

**Comment by shreyb28** [comment]
![image](https://user-images.githubusercontent.com/77260036/104861689-d7185180-596b-11eb-9fe5-ae1c33f533d0.png)
![image](https://user-images.githubusercontent.com/77260036/104861697-ded7f600-596b-11eb-8ec4-c0c69f73954e.png)
![image](https://user-images.githubusercontent.com/77260036/104861702-e5666d80-596b-11eb-9624-e7efbd4c05b6.png)
![image](https://user-images.githubusercontent.com/77260036/104861712-ec8d7b80-596b-11eb-9386-085ed6c21e58.png)
![image](https://user-images.githubusercontent.com/77260036/104861722-f31bf300-596b-11eb-964f-568e58c85695.png)

**Comment by shreyb28** [comment]
Also, is it possible to have more information on the cards when we hover over the appointments.

**Comment by MaTeMaTuK** [comment]
- As far as i can see, you probably use this chart on view(not inside entity). So I recommend change Is SubGrid value to No.
- No. Tooltip shows name, progress, start and end time only for now.

**Comment by shreyb28** [comment]
thankyou

**Comment by MaTeMaTuK** [comment]
Good. If you have any other questions please open the new ticket.
