### ISSUE TITLE
Horizontal scroll not working without scrollbar when rows take 100% height

### ISSUE THREAD

**Issue by Andrea-Bosca** [MaTeMaTuK/pcf-universal-gantt-chart#8]
Hi @MaTeMaTuK,

I have found an issue with the horizontal scroll when there are too many rows (or when row's height make the component trigger the vertical scroll) in the Gantt chart.

In short, in this particular case, our Mac users, or Windows users that has a mouse with the horizontal scroller (ex. Logitech MX Master series), can't scroll the Gantt horizontaly; Mac user's can't see the bottom horizontal scrollbar, Windows users can see and user the scrollbar.

I guess this is caused by the double scrollbar (horizontal and vertical) but it's very annoying; I know that setting 100% height in PCF is very painful 😄

Is it possible to have it fixed?

Great PCF BTW 😃 

Best regards,
Andrea

**Comment by MaTeMaTuK** [comment]
Hi,
Thanks you.
It's very unexpected bug :)
I can try do something with this. But you have workaround. You may try ⇠ ⇡ ⇢ ⇣ buttons as workaround.

**Comment by MaTeMaTuK** [comment]
Hi @Andrea-Bosca,
Could you please test this demo ?
https://matematuk.github.io/gantt-task-react/
Does your mouse scroll horizontally the 2nd example ?

**Comment by MaTeMaTuK** [comment]
Fixed. Please try a new version
