### ISSUE TITLE
Control does not work well in form section

### ISSUE THREAD

**Issue by RamelloEma** [MaTeMaTuK/pcf-universal-gantt-chart#9]
When i add this custom control on the form,  the view doesn't work well, it doesn't expand properly.
I try to change the properties of the form but it doesn't work.

example:
![image](https://user-images.githubusercontent.com/27794347/108881133-c188ee00-75e1-11eb-977d-376769ebde3d.png)

Thanks for the custom control!!

**Comment by MaTeMaTuK** [comment]
Hi, please set IsSubgrid value as yes.

**Comment by RamelloEma** [comment]
Oh, that's great! Thanks!!
